config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  concern :commentable do
    resources :comments, only: [:create]
  end

  concern :votable do
    match 'upvote', to: 'votes#upvote', via: :post
    match 'downvote', to: 'votes#downvote', via: :post
  end

  resources :articles, only: [:new, :create, :show, :index], concerns: [:commentable, :votable]
  resources :comments, only: [], concerns: [:commentable, :votable]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update], path: 'reset', as: :reset

  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Votable

  belongs_to :user
  has_many :comments, as: :commentable

  PER_PAGE = 20
  validates :url, :title, presence: true
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates_length_of :title, in: 1..255

  def comment_count
    self.comments.inject(self.comments.count) { |sum, comment| sum + comment.reply_count }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  helper_method :page, :total_pages, :offset
  before_action :require_logged_in, only: [:new, :create]

  def index
    @articles = Article.offset(offset).limit(Article::PER_PAGE).order(created_at: :desc)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to :articles
    else
      flash.now[:error] = 'Article was not posted—please correct fields below.'
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  private
  def article_params
    params.require(:article).permit(:title, :url)
  end

  def page
    @page ||= [1, params[:page_number].to_i].max
  end

  def total_pages
    @total_pages = (Float(Article.count) / Float(Article::PER_PAGE)).ceil
  end

  def offset
    (page - 1) * Article::PER_PAGE
  end

end

app/views/articles/index.html.slim
- @articles.each.with_index(offset + 1) do |article, index|
  .article
    .num= link_to index, article
    .article-detail
      = render partial: 'components/vote', locals: { votable: article }
      .article-wrapper
        h2.title= link_to article.url do
          => article.title
          span= "(#{URI(article.url).host})"
        .user
          span class='oi' data-glyph='person' title='person' aria-hidden="true"
          = article.user.try(:username) || 'anonymous'
        .post-time
          span class='oi' data-glyph='clock' title='clock' aria-hidden="true"
          = time_ago_in_words(article.created_at) + ' ago'
        .comments= link_to article do
          span class='oi' data-glyph='chat' title='chat' aria-hidden="true"
          | comments (#{article.comment_count})

.page-numbers
  - if total_pages > 1
    - 1.upto(total_pages) do |n|
      - page_class = n == page ? 'current-page' : nil
      = link_to n, articles_path(page_number: (n)), class: page_class

app/views/articles/new.html.slim
= simple_form_for @article do |f|
  = f.input :title, label: 'Article Title'
  = f.input :url, label: 'URL'
  = f.button :submit

app/views/articles/show.html.slim
#article-show.article-detail
  .article-wrapper
    h2.title= link_to @article.url do
      => @article.title
      span= "(#{URI(@article.url).host})"
    .user
      span class='oi' data-glyph='person' title='person' aria-hidden="true"
      = @article.user ? @article.user.username : 'anonymous'
    .post-time
      span class='oi' data-glyph='clock' title='clock' aria-hidden="true"
      = time_ago_in_words(@article.created_at) + ' ago'

#article-comments
  h1
    span class='oi' data-glyph='chat' title='chat' aria-hidden="true"
    | comments (#{@article.comment_count})
  - if logged_in?
    = simple_form_for [@article, @comment] do |f|
      = f.input :body, label: false
      = f.submit 'Post Comment'
  - else
    p
      span class='oi' data-glyph='warning' title='warning' aria-hidden="true"
      | You must be logged in to comment. #{ link_to 'Login', login_path }
  #all-comments
    = render @article.comments