config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  concern :commentable do
    resources :comments, only: [:create]
  end

  concern :votable do
    match 'upvote', to: 'votes#upvote', via: :post
    match 'downvote', to: 'votes#downvote', via: :post
  end

  resources :articles, only: [:new, :create, :show, :index], concerns: [:commentable, :votable]
  resources :comments, only: [], concerns: [:commentable, :votable]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update], path: 'reset', as: :reset

  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HaxxorNews
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name="viewport" content='width=device-width initial-scale=1'
  body
    #main-container
      header
        = link_to root_path do
          h1= 'haxxor news'
        .log-links
          - if logged_in?
            strong= current_user.username
            br
            = link_to 'logout', logout_path
          - else
            = link_to 'sign up', signup_path
            br
            = link_to 'login', login_path
        .new-post= link_to new_article_path do
            | new post
      #flash
        - flash.each do |key, value|
          = content_tag(:div, id: "flash-#{key}") do
            = content_tag(:span, value, class: "alert alert-#{key}")

      = yield
      = javascript_include_tag 'application', 'data-turbolinks-track' => true